function showForElem ( boxName, content ) {
	var showBox = document.getElementById( '' + boxName );

	showBox.innerHTML = '' + content;
	showBox.style.border = "1px solid red";
}

function testAccessKeyOfAnch () {
	var anchor = document.getElementById('a_anch1');
	anchor.accessKey = "w";
}

function testCharsetOfAnch () {
	var anchor = document.getElementById('a_anch2');

	anchor.charset = "GB2312";
}

function testHrefOfAnch () {
	var anchor = document.getElementById('a_anch3');

	var content = "The href of anchor is: " + anchor.href;

	showForElem( 'showbox_anch3', content );
}

function testHreflangOfAnch () {
	var anchor = document.getElementById('a_anch4');

	var content = "The hreflang of anchor is: " + anchor.hreflang;

	showForElem( 'showbox_anch4', content );
}

function testIdOfAnch () {
	var anchor = document.getElementById('a_anch5');

	var content = "The id of anchor is: " + anchor.id;

	showForElem( 'showbox_anch5', content );
}

function testInnerHTMLOfAnch () {
	var anchor = document.getElementById('a_anch6');

	anchor.innerHTML = "www.google.com(Generated by innerHTML)";
}

function testNameOfAnch () {
	var anchor = document.getElementById('a_anch7');

	var content = "The name of anchor is: " + anchor.name;

	showForElem( 'showbox_anch7', content );
}

function testRelOfAnch () {
	var anchor = document.getElementById('a_anch8');

	var content = "The rel of anchor is: " + anchor.rel;

	showForElem( 'showbox_anch8', content );
}

function testRevOfAnch () {
	var anchor = document.getElementById('a_anch9');

	var content = "The rev of anchor is: " + anchor.rev;

	showForElem( 'showbox_anch9', content );
}

function testTargetOfAnch () {
	var anchor = document.getElementById('a_anch11');

	anchor.target = "_blank";
}

function testTabIndexOfAnch () {
	var anchor1 = document.getElementById('a1_anch12');
	var anchor2 = document.getElementById('a2_anch12');

	anchor1.tabIndex = "2";
	anchor2.tabIndex = "1";
}

function testTypeOfAnch () {
	var anchor = document.getElementById('a_anch13');

	var content = "The type of anchor is: " + anchor.type;

	showForElem( 'showbox_anch13', content );
}

function testFocusFuncOfAnch ( id ) {
	var obj = document.getElementById('' + id );
	obj.focus();
}

function testBlurFuncOfAnch ( id ) {
	var obj = document.getElementById('' + id );
	obj.blur();

}